# Generated by Django 5.2.2 on 2026-04-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicehistory',
            name='source',
            field=models.CharField(default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='voicehistory',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
