# Generated by Django 5.2.13 on 2026-05-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0002_voicehistory_source_alter_voicehistory_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicehistory',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='voicehistory',
            name='mode',
            field=models.CharField(default='accent', max_length=20),
        ),
    ]
